mp.messaging.incoming.orders.bootstrap.servers=${KAFKA_CLUSTER_ENDPOINT:kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092}

mp.messaging.incoming.orders.connector=smallrye-kafka
mp.messaging.incoming.orders.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.orders.value.deserializer=br.com.redhat.dto.OrderDTODeserializer
mp.messaging.incoming.orders.topic=orders
mp.messaging.incoming.orders.group.id=${CONSUMER_GROUP_ID:orders-consumer-group}

%dev.mp.messaging.incoming.orders.ssl.truststore.location=${KAFKA_TRUSTSTORE_LOCATION:/home/bcordeir/kafka-projects/kafka-observability/apps/kafka-consumer/src/main/resources/certs/ca.p12}
%dev.mp.messaging.incoming.orders.ssl.truststore.password=${CA_PASSWORD}
%dev.mp.messaging.incoming.orders.ssl.truststore.type=PKCS12

## para poder utilizar SCRAM-SHA-512
%dev.kafka.security.protocol=SASL_SSL
kafka.security.protocol=SASL_PLAINTEXT
kafka.sasl.mechanism=SCRAM-SHA-512
kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user-consumer" password="${USER_PASSWORD}";

quarkus.openshift.build-strategy=docker
