mp.messaging.outgoing.orders.bootstrap.servers=${KAFKA_CLUSTER_ENDPOINT:kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093}

mp.messaging.outgoing.orders.connector=smallrye-kafka
mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.orders.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.orders.topic=orders

mp.messaging.outgoing.orders.ssl.truststore.location=${KAFKA_TRUSTSTORE_LOCATION:/home/bcordeir/kafka-projects/kafka-observability/apps/kafka-producer/src/main/resources/certs/ca.p12}
mp.messaging.outgoing.orders.ssl.truststore.password=${CA_PASSWORD}
mp.messaging.outgoing.orders.ssl.truststore.type=PKCS12

## para poder utilizar SCRAM-SHA-512
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=SCRAM-SHA-512
kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user-producer" password="${USER_PASSWORD}";

## essa configuracao seria para kafka.security.protocol=SSL e porta 9094 ##
### user certificate ###
# mp.messaging.outgoing.orders.ssl.keystore.location=/home/bcordeir/kafka-projects/kafka-observability/kafka-user-producer.p12
# mp.messaging.outgoing.orders.ssl.keystore.password=${USER_PASSWORD}
# mp.messaging.outgoing.orders.ssl.key.password=${USER_PASSWORD}
# mp.messaging.outgoing.orders.ssl.keystore.type=PKCS12
### end user certificate ###